import 'package:soundconverge/models/chat.model.dart';

final List<BotChat> chatdata = [
  BotChat(message: 'hello', rid: 'bot', sid: 'usr'),
  BotChat(message: 'heyaa', sid: 'bot', rid: 'usr'),
  BotChat(message: 'hello', rid: 'bot', sid: 'usr'),
  BotChat(message: 'heyaa', sid: 'bot', rid: 'usr'),
  BotChat(message: 'hello', rid: 'bot', sid: 'usr'),
  BotChat(
      message: 'Following song found over these platforms:',
      sid: 'bot',
      rid: 'usr',
      appleMusicUrl: 'a',
      coverImgUrl: 'https://picsum.photos/200',
      jioSaavanUrl: 'a',
      ytMusicUrl: 'a'),
  BotChat(message: 'heyaa', sid: 'bot', rid: 'usr'),
  BotChat(message: 'hello', rid: 'bot', sid: 'usr'),
  BotChat(message: 'hello', rid: 'bot', sid: 'usr'),
  BotChat(message: 'heyaa', sid: 'bot', rid: 'usr'),
  BotChat(message: 'hello', rid: 'bot', sid: 'usr'),
  BotChat(
      message: 'Following song found over these platforms:',
      sid: 'bot',
      rid: 'usr',
      spotifyUrl: 'a',
      appleMusicUrl: 'a',
      coverImgUrl: 'https://picsum.photos/200'),
  BotChat(message: 'heyaa', sid: 'bot', rid: 'usr'),
  BotChat(message: 'hello', rid: 'bot', sid: 'usr'),
  BotChat(message: 'heyaa', sid: 'bot', rid: 'usr'),
  BotChat(message: 'hello', rid: 'bot', sid: 'usr'),
  BotChat(
      message: 'Following song found over these platforms:',
      sid: 'bot',
      rid: 'usr',
      spotifyUrl: 'a',
      appleMusicUrl: 'a',
      coverImgUrl: 'https://picsum.photos/200',
      gaanaUrl: 'a',
      jioSaavanUrl: 'a',
      ytMusicUrl: 'a'),
];
